### ISSUE TITLE
Genuine enquiries going into spam

### ISSUE THREAD

**Issue by thatswellwizard** [ryangittings/mbk-forms#1]
Hi ryan

I'm having a few issues with genuine enquiries going into spam, Have you had any issues with this?

I've got the recaptcha script in the head on every page and the form specific js is appearing only on pages with the form on.

Thanks

**Comment by ryangittings** [comment]
Hi,

I have had issues with this on one site only. I've found Recaptcha v3 to be a bit hit and miss. There's not much more I can do my end apart from possibly adjusting the score or maybe reverting to v2.

Any suggestions/pull requests are more than welcome!

**Comment by ryangittings** [comment]
Please see updates to the README regarding versions. The app gives you options to use either v2 or v3, which should hopefully solve your issue!
